### ISSUE TITLE
IP en producción

### ISSUE THREAD

**Issue by asiermusa** [soybackend/php-redis-node-sockets#1]
Hola,

Gracias por la repo, está muy sencillo y bien explicado. Ahora tengo una duda, en local todo me funciona a la perfección, pero no consigo entender como poner esto en producción.

1. El backend en PHP y REDIS por una parte tienen una IP.

2. El servidor node corre en otra IP. 

No entiendo en que punto se hace la conexión entre el servidor REDIS y el servidor NODE.

Gracias!

**Comment by soybackend** [comment]
Hola!
Listo mira, desde PHP para poner un mensaje en redis, debes apuntar a la ip y puedo adecuado en la creación del cliente de redis. Esto ocurre en la [línea 5 ](https://github.com/soybackend/php-redis-node-sockets/blob/master/index.php#L5).

Ahora, para que node pueda leer los mensajes de redis que se encuentra en otra ip, debes configurar esa ip y puerto en la [linea 8](https://github.com/soybackend/php-redis-node-sockets/blob/master/server.js#L8) en la cual debes configurarlo como indica [la documentación ](https://github.com/NodeRedis/node-redis#rediscreateclient).

Y listo! cualquier cosa con gusto te ayudo a resolver tus dudas :)
